name: Security scan

on:
  push:
    branches:
      - "**"

jobs:
  trivy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create Trivy results directory
        run: mkdir -p trivy-results

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "github"
          output: "trivy-results/trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results/trivy-results.sarif
